/*	Author:		Kyle Foreman (kforeman@post.harvard.edu)
	Date:		4 January 2012
	Purpose:	List of countries and their corresponding codes for the GBD database
*/

geo_list = [
{name: 'Global', code: 'G'},
{name: 'Developing', code: 'D0'},
{name: 'Developed', code: 'D1'},
{name: "East Asia/Pacific",code: 'SR_6',SR:6},
{name: "Asia, East",code: 'R_3',SR:6,R:3},
{name: "China",code: 'CHN',SR:6,R:3},
{name: "Korea, Democratic People's Republic of",code: 'PRK',SR:6,R:3},
{name: "Taiwan",code: 'TWN',SR:6,R:3},
{name: "Asia, Southeast",code: 'R_5',SR:6,R:5},
{name: "Cambodia",code: 'KHM',SR:6,R:5},
{name: "Indonesia",code: 'IDN',SR:6,R:5},
{name: "Lao People's Democratic Republic",code: 'LAO',SR:6,R:5},
{name: "Malaysia",code: 'MYS',SR:6,R:5},
{name: "Maldives",code: 'MDV',SR:6,R:5},
{name: "Myanmar",code: 'MMR',SR:6,R:5},
{name: "Philippines",code: 'PHL',SR:6,R:5},
{name: "Sri Lanka",code: 'LKA',SR:6,R:5},
{name: "Thailand",code: 'THA',SR:6,R:5},
{name: "Timor-Leste",code: 'TLS',SR:6,R:5},
{name: "Viet Nam",code: 'VNM',SR:6,R:5},
{name: "Oceania",code: 'R_17',SR:6,R:17},
{name: "Fiji",code: 'FJI',SR:6,R:17},
{name: "Kiribati",code: 'KIR',SR:6,R:17},
{name: "Marshall Islands",code: 'MHL',SR:6,R:17},
{name: "Micronesia, Federated States of",code: 'FSM',SR:6,R:17},
{name: "Papua New Guinea",code: 'PNG',SR:6,R:17},
{name: "Samoa",code: 'WSM',SR:6,R:17},
{name: "Solomon Islands",code: 'SLB',SR:6,R:17},
{name: "Tonga",code: 'TON',SR:6,R:17},
{name: "Vanuatu",code: 'VUT',SR:6,R:17},
{name: "Eastern Europe/Central Asia",code: 'SR_2',SR:2},
{name: "Asia, Central",code: 'R_2',SR:2,R:2},
{name: "Armenia",code: 'ARM',SR:2,R:2},
{name: "Azerbaijan",code: 'AZE',SR:2,R:2},
{name: "Georgia",code: 'GEO',SR:2,R:2},
{name: "Kazakhstan",code: 'KAZ',SR:2,R:2},
{name: "Kyrgyzstan",code: 'KGZ',SR:2,R:2},
{name: "Mongolia",code: 'MNG',SR:2,R:2},
{name: "Tajikistan",code: 'TJK',SR:2,R:2},
{name: "Turkmenistan",code: 'TKM',SR:2,R:2},
{name: "Uzbekistan",code: 'UZB',SR:2,R:2},
{name: "Europe, Central",code: 'R_8',SR:2,R:8},
{name: "Albania",code: 'ALB',SR:2,R:8},
{name: "Bosnia and Herzegovina",code: 'BIH',SR:2,R:8},
{name: "Bulgaria",code: 'BGR',SR:2,R:8},
{name: "Croatia",code: 'HRV',SR:2,R:8},
{name: "Czech Republic",code: 'CZE',SR:2,R:8},
{name: "Hungary",code: 'HUN',SR:2,R:8},
{name: "Macedonia, the Former Yugoslav Republic of",code: 'MKD',SR:2,R:8},
{name: "Montenegro",code: 'MNE',SR:2,R:8},
{name: "Poland",code: 'POL',SR:2,R:8},
{name: "Romania",code: 'ROU',SR:2,R:8},
{name: "Serbia",code: 'SRB',SR:2,R:8},
{name: "Slovakia",code: 'SVK',SR:2,R:8},
{name: "Slovenia",code: 'SVN',SR:2,R:8},
{name: "Europe, Eastern",code: 'R_9',SR:2,R:9},
{name: "Belarus",code: 'BLR',SR:2,R:9},
{name: "Estonia",code: 'EST',SR:2,R:9},
{name: "Latvia",code: 'LVA',SR:2,R:9},
{name: "Lithuania",code: 'LTU',SR:2,R:9},
{name: "Moldova",code: 'MDA',SR:2,R:9},
{name: "Russian Federation",code: 'RUS',SR:2,R:9},
{name: "Ukraine",code: 'UKR',SR:2,R:9},
{name: "High Income",code: 'SR_1',SR:1},
{name: "Asia Pacific, High Income",code: 'R_1',SR:1,R:1},
{name: "Brunei Darussalam",code: 'BRN',SR:1,R:1},
{name: "Japan",code: 'JPN',SR:1,R:1},
{name: "Korea, Republic of",code: 'KOR',SR:1,R:1},
{name: "Singapore",code: 'SGP',SR:1,R:1},
{name: "Australasia",code: 'R_6',SR:1,R:6},
{name: "Australia",code: 'AUS',SR:1,R:6},
{name: "New Zealand",code: 'NZL',SR:1,R:6},
{name: "Europe, Western",code: 'R_10',SR:1,R:10},
{name: "Andorra",code: 'AND',SR:1,R:10},
{name: "Austria",code: 'AUT',SR:1,R:10},
{name: "Belgium",code: 'BEL',SR:1,R:10},
{name: "Cyprus",code: 'CYP',SR:1,R:10},
{name: "Denmark",code: 'DNK',SR:1,R:10},
{name: "Finland",code: 'FIN',SR:1,R:10},
{name: "France",code: 'FRA',SR:1,R:10},
{name: "Germany",code: 'DEU',SR:1,R:10},
{name: "Greece",code: 'GRC',SR:1,R:10},
{name: "Iceland",code: 'ISL',SR:1,R:10},
{name: "Ireland",code: 'IRL',SR:1,R:10},
{name: "Israel",code: 'ISR',SR:1,R:10},
{name: "Italy",code: 'ITA',SR:1,R:10},
{name: "Luxembourg",code: 'LUX',SR:1,R:10},
{name: "Malta",code: 'MLT',SR:1,R:10},
{name: "Netherlands",code: 'NLD',SR:1,R:10},
{name: "Norway",code: 'NOR',SR:1,R:10},
{name: "Portugal",code: 'PRT',SR:1,R:10},
{name: "Spain",code: 'ESP',SR:1,R:10},
{name: "Sweden",code: 'SWE',SR:1,R:10},
{name: "Switzerland",code: 'CHE',SR:1,R:10},
{name: "United Kingdom",code: 'GBR',SR:1,R:10},
{name: "Latin America, Southern",code: 'R_13',SR:1,R:13},
{name: "Argentina",code: 'ARG',SR:1,R:13},
{name: "Chile",code: 'CHL',SR:1,R:13},
{name: "Uruguay",code: 'URY',SR:1,R:13},
{name: "North America, High Income",code: 'R_16',SR:1,R:16},
{name: "Canada",code: 'CAN',SR:1,R:16},
{name: "United States",code: 'USA',SR:1,R:16},
{name: "Latin America/Caribbean",code: 'SR_7',SR:7},
{name: "Caribbean",code: 'R_7',SR:7,R:7},
{name: "Antigua and Barbuda",code: 'ATG',SR:7,R:7},
{name: "Bahamas",code: 'BHS',SR:7,R:7},
{name: "Barbados",code: 'BRB',SR:7,R:7},
{name: "Belize",code: 'BLZ',SR:7,R:7},
{name: "Cuba",code: 'CUB',SR:7,R:7},
{name: "Dominica",code: 'DMA',SR:7,R:7},
{name: "Dominican Republic",code: 'DOM',SR:7,R:7},
{name: "Grenada",code: 'GRD',SR:7,R:7},
{name: "Guyana",code: 'GUY',SR:7,R:7},
{name: "Haiti",code: 'HTI',SR:7,R:7},
{name: "Jamaica",code: 'JAM',SR:7,R:7},
{name: "Saint Lucia",code: 'LCA',SR:7,R:7},
{name: "Saint Vincent and the Grenadines",code: 'VCT',SR:7,R:7},
{name: "Suriname",code: 'SUR',SR:7,R:7},
{name: "Trinidad and Tobago",code: 'TTO',SR:7,R:7},
{name: "Latin America, Andean",code: 'R_11',SR:7,R:11},
{name: "Bolivia",code: 'BOL',SR:7,R:11},
{name: "Ecuador",code: 'ECU',SR:7,R:11},
{name: "Peru",code: 'PER',SR:7,R:11},
{name: "Latin America, Central",code: 'R_12',SR:7,R:12},
{name: "Colombia",code: 'COL',SR:7,R:12},
{name: "Costa Rica",code: 'CRI',SR:7,R:12},
{name: "El Salvador",code: 'SLV',SR:7,R:12},
{name: "Guatemala",code: 'GTM',SR:7,R:12},
{name: "Honduras",code: 'HND',SR:7,R:12},
{name: "Mexico",code: 'MEX',SR:7,R:12},
{name: "Nicaragua",code: 'NIC',SR:7,R:12},
{name: "Panama",code: 'PAN',SR:7,R:12},
{name: "Venezuela",code: 'VEN',SR:7,R:12},
{name: "Latin America, Tropical",code: 'R_14',SR:7,R:14},
{name: "Brazil",code: 'BRA',SR:7,R:14},
{name: "Paraguay",code: 'PRY',SR:7,R:14},
{name: "North Africa/Middle East",code: 'SR_4',SR:4},
{name: "North Africa / Middle East",code: 'R_15',SR:4,R:15},
{name: "Algeria",code: 'DZA',SR:4,R:15},
{name: "Bahrain",code: 'BHR',SR:4,R:15},
{name: "Egypt",code: 'EGY',SR:4,R:15},
{name: "Iran, Islamic Republic of",code: 'IRN',SR:4,R:15},
{name: "Iraq",code: 'IRQ',SR:4,R:15},
{name: "Jordan",code: 'JOR',SR:4,R:15},
{name: "Kuwait",code: 'KWT',SR:4,R:15},
{name: "Lebanon",code: 'LBN',SR:4,R:15},
{name: "Libyan Arab Jamahiriya",code: 'LBY',SR:4,R:15},
{name: "Morocco",code: 'MAR',SR:4,R:15},
{name: "Occupied Palestinian Territory",code: 'PSE',SR:4,R:15},
{name: "Oman",code: 'OMN',SR:4,R:15},
{name: "Qatar",code: 'QAT',SR:4,R:15},
{name: "Saudi Arabia",code: 'SAU',SR:4,R:15},
{name: "Syrian Arab Republic",code: 'SYR',SR:4,R:15},
{name: "Tunisia",code: 'TUN',SR:4,R:15},
{name: "Turkey",code: 'TUR',SR:4,R:15},
{name: "United Arab Emirates",code: 'ARE',SR:4,R:15},
{name: "Yemen",code: 'YEM',SR:4,R:15},
{name: "South Asia",code: 'SR_5',SR:5},
{name: "Asia, South",code: 'R_4',SR:5,R:4},
{name: "Afghanistan",code: 'AFG',SR:5,R:4},
{name: "Bangladesh",code: 'BGD',SR:5,R:4},
{name: "Bhutan",code: 'BTN',SR:5,R:4},
{name: "India",code: 'IND',SR:5,R:4},
{name: "Nepal",code: 'NPL',SR:5,R:4},
{name: "Pakistan",code: 'PAK',SR:5,R:4},
{name: "Sub-Saharan Africa",code: 'SR_3',SR:3},
{name: "Sub-Saharan Africa, Central",code: 'R_18',SR:3,R:18},
{name: "Angola",code: 'AGO',SR:3,R:18},
{name: "Central African Republic",code: 'CAF',SR:3,R:18},
{name: "Congo",code: 'COG',SR:3,R:18},
{name: "Congo, the Democratic Republic of the",code: 'COD',SR:3,R:18},
{name: "Equatorial Guinea",code: 'GNQ',SR:3,R:18},
{name: "Gabon",code: 'GAB',SR:3,R:18},
{name: "Sub-Saharan Africa, East",code: 'R_19',SR:3,R:19},
{name: "Burundi",code: 'BDI',SR:3,R:19},
{name: "Comoros",code: 'COM',SR:3,R:19},
{name: "Djibouti",code: 'DJI',SR:3,R:19},
{name: "Eritrea",code: 'ERI',SR:3,R:19},
{name: "Ethiopia",code: 'ETH',SR:3,R:19},
{name: "Kenya",code: 'KEN',SR:3,R:19},
{name: "Madagascar",code: 'MDG',SR:3,R:19},
{name: "Malawi",code: 'MWI',SR:3,R:19},
{name: "Mauritius",code: 'MUS',SR:3,R:19},
{name: "Mozambique",code: 'MOZ',SR:3,R:19},
{name: "Rwanda",code: 'RWA',SR:3,R:19},
{name: "Seychelles",code: 'SYC',SR:3,R:19},
{name: "Somalia",code: 'SOM',SR:3,R:19},
{name: "Sudan",code: 'SDN',SR:3,R:19},
{name: "Tanzania, United Republic of",code: 'TZA',SR:3,R:19},
{name: "Uganda",code: 'UGA',SR:3,R:19},
{name: "Zambia",code: 'ZMB',SR:3,R:19},
{name: "Sub-Saharan Africa, Southern",code: 'R_20',SR:3,R:20},
{name: "Botswana",code: 'BWA',SR:3,R:20},
{name: "Lesotho",code: 'LSO',SR:3,R:20},
{name: "Namibia",code: 'NAM',SR:3,R:20},
{name: "South Africa",code: 'ZAF',SR:3,R:20},
{name: "Swaziland",code: 'SWZ',SR:3,R:20},
{name: "Zimbabwe",code: 'ZWE',SR:3,R:20},
{name: "Sub-Saharan Africa, West",code: 'R_21',SR:3,R:21},
{name: "Benin",code: 'BEN',SR:3,R:21},
{name: "Burkina Faso",code: 'BFA',SR:3,R:21},
{name: "Cameroon",code: 'CMR',SR:3,R:21},
{name: "Cape Verde",code: 'CPV',SR:3,R:21},
{name: "Chad",code: 'TCD',SR:3,R:21},
{name: "Cote d'Ivoire",code: 'CIV',SR:3,R:21},
{name: "Gambia",code: 'GMB',SR:3,R:21},
{name: "Ghana",code: 'GHA',SR:3,R:21},
{name: "Guinea",code: 'GIN',SR:3,R:21},
{name: "Guinea-Bissau",code: 'GNB',SR:3,R:21},
{name: "Liberia",code: 'LBR',SR:3,R:21},
{name: "Mali",code: 'MLI',SR:3,R:21},
{name: "Mauritania",code: 'MRT',SR:3,R:21},
{name: "Niger",code: 'NER',SR:3,R:21},
{name: "Nigeria",code: 'NGA',SR:3,R:21},
{name: "Sao Tome and Principe",code: 'STP',SR:3,R:21},
{name: "Senegal",code: 'SEN',SR:3,R:21},
{name: "Sierra Leone",code: 'SLE',SR:3,R:21},
{name: "Togo",code: 'TGO',SR:3,R:21}]

